import {defineField, defineType} from 'sanity'

export default defineType({
  name: 'home',
  title: 'Home Page',
  type: 'document',
  groups: [
    {name: 'content', title: 'Content'},
    {name: 'metadata', title: 'Metadata'},
  ],
  fields: [
    defineField({
      name: 'eyebrow',
      title: 'Hero Eyebrow',
      type: 'string',
      description: 'Small text above the main hero line. Example: Nathan Rhys',
      group: 'content',
    }),
    defineField({
      name: 'metadata',
      title: 'Page Metadata',
      type: 'metadata',
      group: 'metadata',
    }),
    defineField({
      name: 'tagline',
      title: 'Hero Tagline',
      type: 'string',
      description: 'The main promise. Example: Fantasy where meaning has weight.',
      validation: (Rule) => Rule.required(),
      group: 'content',
    }),
    defineField({
      name: 'blurb',
      title: 'Hero Blurb',
      type: 'text',
      rows: 3,
      group: 'content',
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero Image',
      type: 'image',
      options: {
        hotspot: true,
      },
      group: 'content',
    }),
    defineField({
      name: 'ctas',
      title: 'Calls to Action',
      type: 'array',
      of: [{type: 'cta'}, {type: 'mailerliteCTA'}],
      group: 'content',
    }),
    defineField({
      name: 'featuredBookKicker',
      title: 'Featured Book Section Kicker',
      type: 'string',
      initialValue: 'Featured Novel',
      group: 'content',
    }),
    defineField({
      name: 'featuredBook',
      title: 'Featured Book',
      type: 'reference',
      to: [{type: 'book'}],
      description: 'Homepage focuses on this book.',
      group: 'content',
    }),
    defineField({
      name: 'pillarsKicker',
      title: 'Pillars Section Kicker',
      type: 'string',
      initialValue: 'What you’ll find here',
      group: 'content',
    }),
    defineField({
      name: 'pillarsHeading',
      title: 'Pillars Section Heading',
      type: 'string',
      initialValue: 'Modern fantasy with a moral spine.',
      group: 'content',
    }),
    defineField({
      name: 'brandPillars',
      title: 'Brand Pillars',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'pillar'}]}],
      validation: (Rule) => Rule.max(3),
      group: 'content',
    }),
    defineField({
      name: 'sections',
      title: 'Sections',
      type: 'array',
      of: [
        {type: 'richTextSection'},
        {type: 'listSection'},
        {type: 'cardsSection'},
        {type: 'web3FormsSection'},
        {type: 'mailerliteSection'},
      ],
      group: 'content',
    }),
    defineField({
      name: 'series',
      title: 'Series',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'series'}]}],
      description: 'Kept for later pages / future use.',
      group: 'content',
    }),
  ],
})
