import book from './book'
import chapter from './chapter'
import home from './home'
import series from './series'
import pillar from './pillar'
import metadata from './metadata'
import cta from './cta'
import navigation from './navigation'
import link from './link'
import layout from './layout'
import standardPage from './standardPage'
import listItem from './listItem'
import richTextSection from './richTextSection'
import listSection from './listSection'
import buttondownEmbed from './buttondownEmbed'
import buttondownEmbedSection from './buttondownEmbedSection'

export const schemaTypes = [book, chapter, home, series, pillar, metadata, cta, navigation, link, layout, standardPage, listItem, richTextSection, listSection, buttondownEmbed, buttondownEmbedSection]
