import book from './book'
import chapter from './chapter'
import home from './home'
import series from './series'
import pillar from './pillar'
import metadata from './metadata'
import cta from './cta'
import navigation from './navigation'
import link from './link'
import layout from './layout'
import standardPage from './standardPage'
import listItem from './listItem'
import richTextSection from './richTextSection'
import listSection from './listSection'
import artist from './artist'
import galleryItem from './galleryItem'
import artistsPage from './artistsPage'
import galleryPage from './galleryPage'
import siteMetadata from './siteMetadata'

import newsletter from './newsletter'
import newsletters from './newsletters'
import newsletterThankYou from './newsletterThankYou'
import footer from './footer'

export const schemaTypes = [book, chapter, home, series, pillar, metadata, cta, navigation, link, layout, standardPage, listItem, richTextSection, listSection, artist, galleryItem, artistsPage, galleryPage, siteMetadata, newsletter, newsletters, newsletterThankYou, footer]
