name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Change to your default branch
  workflow_dispatch:
  repository_dispatch:
    types: [sanity_update]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build Web
        run: npm run build:web
        env:
          # Environment Secrets (production)
          PUBLIC_TURNSTILE_SITE_KEY: ${{ secrets.PUBLIC_TURNSTILE_SITE_KEY }}
          # Environment Variables (production)
          PUBLIC_SANITY_DATASET: ${{ vars.PUBLIC_SANITY_DATASET }}
          SITE_URL: ${{ vars.SITE_URL }}
          WEB3FORMS_REQUIRE_TURNSTILE: ${{ vars.WEB3FORMS_REQUIRE_TURNSTILE }}
          # Repository Secrets
          MAILERLITE_API_KEY: ${{ secrets.MAILERLITE_API_KEY }}
          PUBLIC_MAILERLITE_ACCOUNT_ID: ${{ secrets.PUBLIC_MAILERLITE_ACCOUNT_ID }}
          PUBLIC_SANITY_PROJECT_ID: ${{ secrets.PUBLIC_SANITY_PROJECT_ID }}
          WEB3FORMS_ACCESS_KEY: ${{ secrets.WEB3FORMS_ACCESS_KEY }}
          WEB3FORMS_ACCESS_KEY_CONTACT: ${{ secrets.WEB3FORMS_ACCESS_KEY_CONTACT }}
      - name: Deploy to GitHub Pages (public repo)
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions"
          cd dist/web
          git init
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force https://x-access-token:${{ secrets.NATHAN_RHYS_PUBLIC_SITE__DEPLOY_PAT }}@github.com/bulwarkbookworks/nathan-rhys-site-public.git HEAD:gh-pages
